### ISSUE TITLE
新闻最好贴更正式一点的链接,如有后续也可贴上

### ISSUE THREAD

**Issue by TheKiteRunning** [nullforces/awful#1]
非常好的网页,因为有的直接指向人,不妨寻找更正式的新闻来源

比如:青岛求实:

- [一名女大学生的非正常死亡](http://zqb.cyol.com/html/2012-11/21/nw.D110000zgqnb_20121121_2-07.htm)
- [青岛求实学院相关负责人被追责](http://zqb.cyol.com/html/2012-11/23/nw.D110000zgqnb_20121123_3-07.htm)

另外, 事件的后续也很重要,比如王攀事件:

- [武汉理工回应研究生坠亡事件：停止导师王攀招生资格](http://www.chinanews.com/sh/2018/04-08/8485482.shtml)

**Comment by westudentsunited** [comment]
@TheKiteRunning 很棒的建议呢，请问可以提交一个 Pull Request 么？

**Comment by TheKiteRunning** [comment]
我还不大会用github，先学习一下~
